### PR TITLE
Regen

### PR DESCRIPTION
**Pull request by EPashkin**
Part of gtk-rs/gir#663

cc @GuillaumeGomez

### CODE REVIEW

**Comment by EPashkin** [comment]
@GuillaumeGomez want me replace "stable" to "1.28" too ?

**Comment by EPashkin** [comment]
Sorry, missed that you already change to 1.28.0.
Just fixing clippy then

**Comment by GuillaumeGomez** [comment]
Yes I already did! :)

And thanks! (waiting for CIs...)

**Comment by EPashkin** [comment]
CI passed

**Pull request merged**
